language: python
sudo: false
dist: xenial
cache: pip
os: linux
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
  - "pypy3"
  - "nightly"
jobs:
  include:
    - { python: "2.7", matrix: DJANGO="Django>=1.7,<1.8" }
    - { python: "2.7", matrix: DJANGO=Django>=1.8,<1.9" }
    - { python: "2.7", matrix: DJANGO="Django>=1.9,<1.10" }
    - { python: "2.7", matrix: DJANGO="Django>=1.10,<1.11" }
    - { python: "pypy", matrix: DJANGO="Django>=1.7,<1.8" }
    - { python: "pypy", matrix: DJANGO=Django>=1.8,<1.9" }
    - { python: "pypy", matrix: DJANGO="Django>=1.9,<1.10" }
    - { python: "pypy", matrix: DJANGO="Django>=1.10,<1.11" }
  allow_failures:
    - python: "nightly"
    - python: "3.8-dev"
    - python: "pypy3"

env:
  global:
    - PYTEST_DJANGO=pytest-django==3.6.0
  matrix:
    - DJANGO="Django>=1.11,<1.12"
    - DJANGO="Django>=2.0,<2.1"
    - DJANGO="Django>=2.1,<2.2"

install:
  - pip install $DJANGO
  - pip install -e .[test] $PYTEST_DJANGO
script:
  - coverage run -m py.test advanced_filters
  - pep8 --exclude=*urls.py --exclude=*migrations advanced_filters -v
after_success:
  coveralls
