language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO=1.7
    - python: "2.6"
      env: DJANGO=1.8
env:
  - DJANGO=1.5
  - DJANGO=1.6
  - DJANGO=1.7
  - DJANGO=1.8
install:
  - pip install django==$DJANGO --use-mirrors
  - pip install -e .[test] --use-mirrors
script:
  - coverage run --source=advanced_filters setup.py test
  - pep8 --exclude=*urls.py advanced_filters -v
after_success:
  coveralls