language: python
sudo: false
cache: pip
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
matrix:
  include:
    - python: "3.6"
      env: DJANGO="Django>=1.11,<1.12"
    - python: "3.6"
      env: DJANGO="Django>=2.0,<2.1"
    - python: "3.6"
      env: DJANGO="Django>=2.1,<2.2" PYTEST_DJANGO="pytest-django==3.4.2"
  exclude:
    - python: "2.7"
      env: DJANGO="Django>=2.0,<2.1"
    - python: "2.7"
      env: DJANGO="Django>=2.1,<2.2" PYTEST_DJANGO="pytest-django==3.4.2"
    - python: "3.5"
      env: DJANGO="Django>=1.7,<1.8"
    - python: "3.3"
      env: DJANGO="Django>=1.9,<1.10"
    - python: "3.3"
      env: DJANGO="Django>=1.10,<1.11"
    - python: "3.3"
      env: DJANGO="Django>=1.11,<1.12"
    - python: "3.3"
      env: DJANGO="Django>=2.0,<2.1"
    - python: "pypy"
      env: DJANGO="Django>=2.0,<2.1"
    - python: "3.3"
      env: DJANGO="Django>=2.1,<2.2" PYTEST_DJANGO="pytest-django==3.4.2"
    - python: "3.4"
      env: DJANGO="Django>=2.1,<2.2" PYTEST_DJANGO="pytest-django==3.4.2"
    - python: "pypy"
      env: DJANGO="Django>=2.1,<2.2" PYTEST_DJANGO="pytest-django==3.4.2"
env:
  global:
    - PYTEST_DJANGO=pytest-django==2.9.1
  matrix:
    - DJANGO="Django>=1.7,<1.8"
    - DJANGO="Django>=1.8,<1.9"
    - DJANGO="Django>=1.9,<1.10"
    - DJANGO="Django>=1.10,<1.11"
    - DJANGO="Django>=1.11,<1.12"
    - DJANGO="Django>=2.0,<2.1"
    - DJANGO="Django>=2.1,<2.2" PYTEST_DJANGO="pytest-django==3.4.2"
install:
  - pip install $DJANGO
  - pip install -e .[test] $PYTEST_DJANGO
script:
  - coverage run -m py.test advanced_filters
  - pep8 --exclude=*urls.py --exclude=*migrations advanced_filters -v
after_success:
  coveralls
